# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, builds an image, performs a container image
# scan with Anchore's Syft tool, and uploads the results to the GitHub Dependency
# submission API.

# For more information on the Anchore sbom-action usage
# and parameters, see https://github.com/anchore/sbom-action. For more
# information about the Anchore SBOM tool Syft, see
# https://github.com/anchore/syft
name: Anchore SBOM Scan

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  Download-Syft:
    runs-on: ubuntu-latest
    steps:
      - name: Download Syft
        uses: anchore/sbom-action/download-syft@dependabot/npm_and_yarn/actions/exec-3.0.0
        id: syft

      - run: echo "${{ steps.syft.outputs.cmd }}"

      - run: ${{ steps.syft.outputs.cmd }} version

  Anchore-Build-Scan:
    permissions:
      contents: write # required to upload to the API
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Scan the workspace and upload dependency results
        uses: anchore/sbom-action@dependabot/npm_and_yarn/actions/exec-3.0.0
        with:
          path: .
          artifact-name: workspace.spdx.json
          dependency-snapshot: true

      - name: Scan an image and upload dependency results
        uses: anchore/sbom-action@dependabot/npm_and_yarn/actions/exec-3.0.0
        env:
          SYFT_SCOPE: all-layers
        with:
          image: alpine:latest
          artifact-name: alpine-latest.spdx.json
