name: Check Windows cURL versions
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          md curl
          curl https://curl.se/windows/dl-8.7.1_3/curl-8.7.1_3-win64-mingw.zip > curl/curl.zip
          cd curl
          unzip curl.zip
      - run: sh -c 'PATH="$(pwd)/curl/curl-8.7.1_3-win64-mingw/bin:$PATH" curl --version'
      - run: sh -c "PATH="$(pwd)/curl/curl-8.7.1_3-win64-mingw/bin:$PATH" curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin"
#      - run: sh -c "which sh"
#      - run: sh -c "which curl"
#      - shell: pwsh
#        run: curl --version
