name: Check Windows cURL versions
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          md curl
          curl https://curl.se/windows/dl-8.8.0_3/curl-8.8.0_3-win64-mingw.zip > curl/curl.zip
          cd curl
          unzip curl.zip
      - run: sh -c 'PATH="$(pwd)/curl/bin:$PATH" curl --version'
#      - run: sh -c "which sh"
#      - run: sh -c "which curl"
#      - shell: pwsh
#        run: curl --version
