name: Check Windows cURL versions
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: sh -c "curl --version"
      - run: sh -c "which curl"
      - shell: pwsh
        run: curl --version
