name: "Manual Dispatch"
on:
  workflow_dispatch:
    inputs:
      enable-tmate:
        description: 'Run tmate'
        required: true
        default: 'false'
  pull_request:

jobs:
  go:
    name: "asdf"
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.enable-tmate }}"
      - run: echo "run tmate!"
        if: ${{ github.event.inputs.enable-tmate }}
      - run: echo "run tmate == 'true'"
        if: ${{ github.event.inputs.enable-tmate == 'true' }}
      - run: echo "no running tmate!"
        if: ${{ github.event.inputs.enable-tmate != 'true' }}
