name: "Manual Dispatch"
on:
  workflow_dispatch:
    inputs:
      enable-tmate:
        description: 'Run tmate'
        required: true
        default: 'false'

jobs:
  go:
    name: "asdf"
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.enable-tmate }}"
