name: Test Matrix
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run package
      - run: docker build -t sbom-action-test:latest .
      - run: docker push sbom-action-test:latest localhost:5000
