name: Test Matrix
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    strategy:
      matrix:
        c: [proxy, controller]
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run package
      - run: docker build -t localhost:5000/sbom-action-test-${{ matrix.c }}:latest .
      - run: docker push localhost:5000/sbom-action-test-${{ matrix.c }}:latest
