name: Build Pipeline
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ v* ]
#  release:
#    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - uses: anchore/sbom-action@v0
        with:
          compare-pulls: true
      - run: npm run package
      - run: docker build -t sbom-action-test:latest .
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
      - uses: anchore/sbom-action@v0
        with:
          image: sbom-action-test:latest
          artifact-name: image.spdx.json
      - uses: anchore/sbom-action/publish-sbom@v0
        with:
          sbom-artifact-match: .*.sbom.json$
      - run: echo "Releasing this image..."
        if: ${{ github.event_name == 'release' }}
