name: Create / Edit Release
on:
  release:
    types: [ published, created, edited ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action/publish-sbom@v0
        with:
          sbom-artifact-match: .*.spdx.json$
