name: Create / Edit Release
on:
  release:
    types: [ created, edited ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: kzantow-anchore/sbom-action@chore/update-github-artifact-client
        with:
          sbom-artifact-match: .*.spdx.json$
