name: Create / Edit Release
on:
  release:
    types: [ created, edited ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action@main
        with:
          sbom-artifact-match: .*.spdx.json$
