name: Test Scan
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/scan-action@v3
        id: scan
        continue-on-error: true
        with:
          image: centos:6
      - run: echo Scan Failed!
        if: ${{steps.scan.outcome == 'failure'}}
